# Wrangler configuration for Cloudflare Pages
name = "chicas-cleaning-client"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Pages configuration
[build]
command = "npm run build"
destination = ".vercel/output/static"

[build.environment_variables]
NODE_VERSION = "18"
