# Wrangler configuration for Cloudflare Pages
name = "chicas-cleaning-client"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[build]
command = "npm run build"